services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-prod
    image: advmanoelneto-web:latest
    environment:
      WEB_PORT: '3000'
    networks:
      - crononest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=crononest'
        - 'traefik.http.routers.adv-manoel-web.rule=Host(`${FRONT_DOMAIN}`)'
        - 'traefik.http.routers.adv-manoel-web.entrypoints=${TRAEFIK_ENTRYPOINT:-websecure}'
        - 'traefik.http.routers.adv-manoel-web.tls.certresolver=${TRAEFIK_CERTRESOLVER:-letsencryptresolver}'
        - 'traefik.http.services.adv-manoel-web.loadbalancer.server.port=3000'

networks:
  crononest:
    external: true
    name: crononest
